
package ec.fin.coop15abril.servicios.municipio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiciosMunicipioCliente", targetNamespace = "http://municipio.servicios.coop15abril.fin.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiciosMunicipioCliente {


    /**
     * 
     * @param identificacionPagador
     * @param canal
     * @param identificacionTitular
     * @return
     *     returns ec.fin.coop15abril.servicios.municipio.ResultadoConsultaResumen
     * @throws ServiciosFault
     */
    @WebMethod
    @WebResult(name = "ConsultaResumen", targetNamespace = "")
    @RequestWrapper(localName = "consultaResumen", targetNamespace = "http://municipio.servicios.coop15abril.fin.ec/", className = "ec.fin.coop15abril.servicios.municipio.ConsultaResumen")
    @ResponseWrapper(localName = "consultaResumenResponse", targetNamespace = "http://municipio.servicios.coop15abril.fin.ec/", className = "ec.fin.coop15abril.servicios.municipio.ConsultaResumenResponse")
    public ResultadoConsultaResumen consultaResumen(
        @WebParam(name = "identificacionPagador", targetNamespace = "")
        String identificacionPagador,
        @WebParam(name = "identificacionTitular", targetNamespace = "")
        String identificacionTitular,
        @WebParam(name = "canal", targetNamespace = "")
        Canal canal)
        throws ServiciosFault
    ;

    /**
     * 
     * @param identificacionPagador
     * @param canal
     * @param identificacionTitular
     * @return
     *     returns ec.fin.coop15abril.servicios.municipio.ResultadoConsulta
     * @throws ServiciosFault
     */
    @WebMethod
    @WebResult(name = "Consulta", targetNamespace = "")
    @RequestWrapper(localName = "consulta", targetNamespace = "http://municipio.servicios.coop15abril.fin.ec/", className = "ec.fin.coop15abril.servicios.municipio.Consulta")
    @ResponseWrapper(localName = "consultaResponse", targetNamespace = "http://municipio.servicios.coop15abril.fin.ec/", className = "ec.fin.coop15abril.servicios.municipio.ConsultaResponse")
    public ResultadoConsulta consulta(
        @WebParam(name = "identificacionPagador", targetNamespace = "")
        String identificacionPagador,
        @WebParam(name = "identificacionTitular", targetNamespace = "")
        String identificacionTitular,
        @WebParam(name = "canal", targetNamespace = "")
        Canal canal)
        throws ServiciosFault
    ;

    /**
     * 
     * @param infoPago
     * @return
     *     returns ec.fin.coop15abril.servicios.municipio.PagoOut
     * @throws ServiciosFault
     */
    @WebMethod
    @WebResult(name = "Pago", targetNamespace = "")
    @RequestWrapper(localName = "pago", targetNamespace = "http://municipio.servicios.coop15abril.fin.ec/", className = "ec.fin.coop15abril.servicios.municipio.Pago")
    @ResponseWrapper(localName = "pagoResponse", targetNamespace = "http://municipio.servicios.coop15abril.fin.ec/", className = "ec.fin.coop15abril.servicios.municipio.PagoResponse")
    public PagoOut pago(
        @WebParam(name = "InfoPago", targetNamespace = "")
        PagoIn infoPago)
        throws ServiciosFault
    ;

    /**
     * 
     * @param infoPago
     * @return
     *     returns ec.fin.coop15abril.servicios.municipio.PagoOut
     * @throws ServiciosFault
     */
    @WebMethod
    @WebResult(name = "PagoResumen", targetNamespace = "")
    @RequestWrapper(localName = "pagoResumen", targetNamespace = "http://municipio.servicios.coop15abril.fin.ec/", className = "ec.fin.coop15abril.servicios.municipio.PagoResumen")
    @ResponseWrapper(localName = "pagoResumenResponse", targetNamespace = "http://municipio.servicios.coop15abril.fin.ec/", className = "ec.fin.coop15abril.servicios.municipio.PagoResumenResponse")
    public PagoOut pagoResumen(
        @WebParam(name = "InfoPago", targetNamespace = "")
        PagoInResumen infoPago)
        throws ServiciosFault
    ;

}
