
package com.cooperativa15abril.facilito.controladorsoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicoIntegracionFacilito", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", wsdlLocation = "http://200.100.1.47:8001/Servicios/Facilito/Cliente?wsdl")
public class ServicoIntegracionFacilito_Service
    extends Service
{

    private final static URL SERVICOINTEGRACIONFACILITO_WSDL_LOCATION;
    private final static WebServiceException SERVICOINTEGRACIONFACILITO_EXCEPTION;
    private final static QName SERVICOINTEGRACIONFACILITO_QNAME = new QName("http://controladorsoap.facilito.cooperativa15abril.com/", "ServicoIntegracionFacilito");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://200.100.1.47:8001/Servicios/Facilito/Cliente?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICOINTEGRACIONFACILITO_WSDL_LOCATION = url;
        SERVICOINTEGRACIONFACILITO_EXCEPTION = e;
    }

    public ServicoIntegracionFacilito_Service() {
        super(__getWsdlLocation(), SERVICOINTEGRACIONFACILITO_QNAME);
    }

    public ServicoIntegracionFacilito_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICOINTEGRACIONFACILITO_QNAME, features);
    }

    public ServicoIntegracionFacilito_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICOINTEGRACIONFACILITO_QNAME);
    }

    public ServicoIntegracionFacilito_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICOINTEGRACIONFACILITO_QNAME, features);
    }

    public ServicoIntegracionFacilito_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoIntegracionFacilito_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicoIntegracionFacilito
     */
    @WebEndpoint(name = "ServicoIntegracionFacilitoPort")
    public ServicoIntegracionFacilito getServicoIntegracionFacilitoPort() {
        return super.getPort(new QName("http://controladorsoap.facilito.cooperativa15abril.com/", "ServicoIntegracionFacilitoPort"), ServicoIntegracionFacilito.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoIntegracionFacilito
     */
    @WebEndpoint(name = "ServicoIntegracionFacilitoPort")
    public ServicoIntegracionFacilito getServicoIntegracionFacilitoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controladorsoap.facilito.cooperativa15abril.com/", "ServicoIntegracionFacilitoPort"), ServicoIntegracionFacilito.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICOINTEGRACIONFACILITO_EXCEPTION!= null) {
            throw SERVICOINTEGRACIONFACILITO_EXCEPTION;
        }
        return SERVICOINTEGRACIONFACILITO_WSDL_LOCATION;
    }

}
