
package com.cooperativa15abril.facilito.controladorsoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.sw_wcf_entidades.EntidadesFinancierasCIConsultaEntidades;
import org.datacontract.schemas._2004._07.sw_wcf_entidades.INTCUPOResponseCupo;
import org.datacontract.schemas._2004._07.sw_wcf_entidades.INTResplyConsulta;
import org.datacontract.schemas._2004._07.sw_wcf_entidades.INTResplyPago;
import org.datacontract.schemas._2004._07.sw_wcf_entidades.INTResplyReverso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicoIntegracionFacilito", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/")
@XmlSeeAlso({
    com.cooperativa15abril.facilito.controladorsoap.ObjectFactory.class,
    org.datacontract.schemas._2004._07.sw_wcf_entidades.ObjectFactory.class
})
public interface ServicoIntegracionFacilito {


    /**
     * 
     * @param solicitudreverso
     * @return
     *     returns org.datacontract.schemas._2004._07.sw_wcf_entidades.INTResplyReverso
     * @throws ExcepcionServicio_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reverso", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.Reverso")
    @ResponseWrapper(localName = "reversoResponse", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.ReversoResponse")
    public INTResplyReverso reverso(
        @WebParam(name = "solicitudreverso", targetNamespace = "")
        SolicitudReverso solicitudreverso)
        throws ExcepcionServicio_Exception
    ;

    /**
     * 
     * @param solicitudconfirmacion
     * @return
     *     returns org.datacontract.schemas._2004._07.sw_wcf_entidades.INTResplyPago
     * @throws ExcepcionServicio_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmacion", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.Confirmacion")
    @ResponseWrapper(localName = "confirmacionResponse", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.ConfirmacionResponse")
    public INTResplyPago confirmacion(
        @WebParam(name = "solicitudconfirmacion", targetNamespace = "")
        SolicitudConfirmacion solicitudconfirmacion)
        throws ExcepcionServicio_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.datacontract.schemas._2004._07.sw_wcf_entidades.EntidadesFinancierasCIConsultaEntidades
     * @throws ExcepcionServicio_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultasEntidadesCI", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.ConsultasEntidadesCI")
    @ResponseWrapper(localName = "consultasEntidadesCIResponse", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.ConsultasEntidadesCIResponse")
    public EntidadesFinancierasCIConsultaEntidades consultasEntidadesCI(
        @WebParam(name = "arg0", targetNamespace = "")
        SolicitudConsultaEntidad arg0)
        throws ExcepcionServicio_Exception
    ;

    /**
     * 
     * @param solicitudconsultacupo
     * @return
     *     returns org.datacontract.schemas._2004._07.sw_wcf_entidades.INTCUPOResponseCupo
     * @throws ExcepcionServicio_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaCupo", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.ConsultaCupo")
    @ResponseWrapper(localName = "consultaCupoResponse", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.ConsultaCupoResponse")
    public INTCUPOResponseCupo consultaCupo(
        @WebParam(name = "solicitudconsultacupo", targetNamespace = "")
        SolicitudConsultaCupo solicitudconsultacupo)
        throws ExcepcionServicio_Exception
    ;

    /**
     * 
     * @param solicitudconsulta
     * @return
     *     returns org.datacontract.schemas._2004._07.sw_wcf_entidades.INTResplyConsulta
     * @throws ExcepcionServicio_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaRedFacilito", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.ConsultaRedFacilito")
    @ResponseWrapper(localName = "consultaRedFacilitoResponse", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.ConsultaRedFacilitoResponse")
    public INTResplyConsulta consultaRedFacilito(
        @WebParam(name = "solicitudconsulta", targetNamespace = "")
        SolicitudConsulta solicitudconsulta)
        throws ExcepcionServicio_Exception
    ;

    /**
     * 
     * @param solicitudrecarga
     * @return
     *     returns com.cooperativa15abril.facilito.controladorsoap.RespuestaRecarga
     * @throws ExcepcionServicio_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recargas", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.Recargas")
    @ResponseWrapper(localName = "recargasResponse", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.RecargasResponse")
    public RespuestaRecarga recargas(
        @WebParam(name = "solicitudrecarga", targetNamespace = "")
        SolicitudRecarga solicitudrecarga)
        throws ExcepcionServicio_Exception
    ;

    /**
     * 
     * @param solicitudpagootp
     * @return
     *     returns org.datacontract.schemas._2004._07.sw_wcf_entidades.INTResplyPago
     * @throws ExcepcionServicio_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitudValidacion", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.SolicitudValidacion")
    @ResponseWrapper(localName = "solicitudValidacionResponse", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.SolicitudValidacionResponse")
    public INTResplyPago solicitudValidacion(
        @WebParam(name = "solicitudpagootp", targetNamespace = "")
        SolicitudPagoOtp solicitudpagootp)
        throws ExcepcionServicio_Exception
    ;

    /**
     * 
     * @param solicitudpago
     * @return
     *     returns com.cooperativa15abril.facilito.controladorsoap.ResultadoProcesoPago
     * @throws ExcepcionServicio_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pago", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.Pago")
    @ResponseWrapper(localName = "pagoResponse", targetNamespace = "http://controladorsoap.facilito.cooperativa15abril.com/", className = "com.cooperativa15abril.facilito.controladorsoap.PagoResponse")
    public ResultadoProcesoPago pago(
        @WebParam(name = "solicitudpago", targetNamespace = "")
        SolicitudPago solicitudpago)
        throws ExcepcionServicio_Exception
    ;

}
